AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'bin/*'
  TargetRubyVersion: 2.6.3
Documentation:
    Enabled: false
Metrics/MethodLength:
    Max: 100
Metrics/LineLength:
    Max: 100
Metrics/BlockLength:
    Max: 100
Metrics/AbcSize:
    Max: 45
Metrics/ParameterLists:
    Max: 7
Metrics/CyclomaticComplexity:
    Max: 30
Metrics/PerceivedComplexity:
    Max: 40
Metrics/ClassLength:
    Max: 200
