development:
    twitter_key: '08eVz6MzaHQlXjWCaNsOnje3Z'
    twitter_secret: 'gU3efQa34BEYPgs8THtYqsbXwHAYlj9gDRw4DfzXjcfvZ7VPny'
    access_token: '2333158698-kWd0IWqRVQO6Mib4IKQMSVXb6zCUgYHFHyLgPKo'
    access_token_secret: 'adG2sEHxXjUifdfC2Ykfkk7jNaljE5yPlTijsq95cVGPE'
production:
    twitter_key: ''
    twitter_secret: ''
    access_token: ''
    access_token_secret: ''
